ticketee/config/routes.rb
Ticketee::Application.routes.draw do

  

  root :to => "projects#index"
  resources :projects
end

ticketee/app/models/project.rb
class Project < ActiveRecord::Base
end

ticketee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ticketee/app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end
end

ticketee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--<title><%= @title || "Ticketee" %></title>-->
  <title>
	<% if content_for?(:title) %>
		<%= yield(:title) %>
	<% else %>
		Ticketee
	<% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% flash.each do |key, value| %>
		<div class='flash' id='<%= key %>'>
		   <%= value %>
        </div>
	<% end %>
    <%= yield %>

</body>
</html>

ticketee/app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

ticketee/app/views/projects/new.html.erb
<h2>New Project</h2>

<%= form_for(@project) do |f|%>
	   <p>
		 <%= f.label :name %><br/>
		 <%= f.text_field :name  %>
	   </p>

	   <p>
		 <%= f.label :description  %><br/>
		 <%= f.text_field :description  %>
	   </p>

	   <p>
		 <br/>
		  <%= f.submit %>
	   </p>

<% end %>